name: CI/CD for Frontend (React + Vite) - Jaya Coin Converter

on:
  push:
    branches:
      - develop

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: .
          retention-days: 1

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        env:
          VITE_API_URL_BACK_END: ${{ secrets.VITE_API_URL_BACK_END }}
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: .

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Initialize Git repository
        run: |
          git init
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Initial commit for Heroku deployment" || echo "No changes to commit"

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Configure Heroku Buildpacks
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_DEBUG: 1
          HEROKU_APP_NAME: frontend-jaya-coin-converter
        run: |
          echo "Logging in to Heroku..."
          export HEROKU_API_KEY="$HEROKU_API_KEY"
          echo "HEROKU_API_KEY is set to: ${HEROKU_API_KEY:0:10}..."

          echo "Clearing existing buildpacks..."
          heroku buildpacks:clear -a $HEROKU_APP_NAME

          echo "Setting heroku/nodejs buildpack..."
          heroku buildpacks:add heroku/nodejs -a $HEROKU_APP_NAME

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: frontend-jaya-coin-converter
          heroku_email: "github-actions@users.noreply.github.com"
          appdir: .
          usedocker: false
          dontuseforce: true