name: Deploy to Heroku

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Create Heroku app if it doesn't exist
        run: |
          if ! heroku apps:info -a frontend-java-coin-converter &> /dev/null; then
            heroku create frontend-java-coin-converter
          fi
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Add Heroku buildpacks
        run: |
          heroku buildpacks:clear -a frontend-java-coin-converter
          heroku buildpacks:set heroku/nodejs -a frontend-java-coin-converter
          heroku buildpacks:add https://github.com/heroku/heroku-buildpack-static.git -a frontend-java-coin-converter
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "frontend-java-coin-converter"
          heroku_email: "guih.smi2@gmail.com"
          appdir: "dist"
        env:
          HD_APP_BASE: "dist"