name: CI/CD para o Front-end(React + Vite) - Jaya Coin Converter

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'    

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build  
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/      
    - name: Initialize Git repository
      run: |
        cd dist
        git init
        git config user.name "Heroku-Deploy"
        git config user.email "deploy@heroku.com"
        git add .
        git commit -m "Prepare dist for Heroku deployment"    
    - name: Deploy para o Heroku - Front-end
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: dist
        procfile: 'web: npm run serve'      