name: CI/CD para o Front-end(React + Vite) - Jaya Coin Converter

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'    

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        env:
            VITE_API_URL_BACK: ${{ secrets.VITE_API_URL_BACK }}
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Install Heroku CLI
         run: |
           curl https://cli-assets.heroku.com/install.sh | sh
           heroku --version
       - name: Deploy to Heroku
         env:
           HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
           HEROKU_APP_NAME: frontend-jaya-coin-converter
         run: |
          echo "Logging in to Heroku..."
          echo "${HEROKU_API_KEY}" | heroku login --api-key
          echo "Deploying to Heroku app: ${HEROKU_APP_NAME}"
          heroku git:remote -a ${HEROKU_APP_NAME}
          git add dist -f
          git commit -m "Deploy built assets"
          git push heroku main --force   